name: Draw Keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/keymap_drawer.config.yaml"

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install keymap-drawer
        run: pip install "keymap-drawer>=0.17.0" "tree-sitter<0.22.0"

      - name: Draw Keymap
        run: |
          mkdir -p img
          # O comando parse transforma seu .keymap em algo que o desenhista entende
          python3 -m keymap_drawer -c config/keymap_drawer.config.yaml parse -z config/sofle.keymap > sofle_layout.yaml
          # O comando draw gera o SVG final
          python3 -m keymap_drawer -c config/keymap_drawer.config.yaml draw sofle_layout.yaml > img/keymap.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add img/keymap.svg
          git commit -m "Update keymap SVG" || echo "No changes to commit"
          git push
